#!/usr/bin/python3

import json

json_file = './schacon.repos.json'
chacon_csv = './chacon.csv'

with open(json_file, 'r') as file:
    data = json.load(file)


with open(chacon_csv, 'w') as csv_file:
    for repo in data[:5]:
        name = repo.get("name", "")
        html_url = repo.get("html_url", "")
        updated_at = repo.get("updated_at", "")
        visibility = repo.get("visibility", "")
        csv_line = f"{name},{html_url},{updated_at},{visibility}\n"

        csv_file.write(csv_line)
